#from . import config_settings
#from . import equipment_installation
from . import maintenance_request
#from . import maintenance_equipment
#from . import product_template
#from . import stock_picking
#from . import task_line
#from . import job_line
#from . import res_partner